### ISSUE TITLE
Database is missing

### ISSUE THREAD

**Issue by raeevy** [killdns/zf3-simple-cms#1]
I am new to send and wanted to try a pre-installed CMS architecture. I came across your work but it seems I cannot import the database schema. Either it would be a export file or probable is created using CLI. Can you please help?

**Comment by killdns** [comment]
Hello! Sorry for the long wait. It seems like this dump should work, but it's not for sure [CLICK](https://gist.github.com/killdns/ec0e1a6aef3f3591e3ca9d4926ef0d33)
